export const INTERNAL_ENDPOINTS = {
  GET_SOCKET: '/users/ws-token',
  LOGIN: '/auth/login',
  UPDATE_USER: '/users/',
  WATCHLIST: '/watchlist',
  GET_NOTIFICATIONS: '/notifications',
  GET_SIGNALS: '/notifications/signals',
  GET_UNREAD_COUNT: '/notifications/unread/count',
  MARK_AS_READ: '/notifications',
  MARK_ALL_AS_READ: '/notifications/read-all',
  DELETE_NOTIFICATION: '/notifications',
  DELETE_ALL_NOTIFICATIONS: '/notifications',
  CHATS: '/chats',
  CHAT_MESSAGES: '/messages',
};
